name: Build and Upload Binary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # 根据项目的需要设置Go版本

    - name: Build the binary
      run: |
        cd cmd/service
        go build -o ../../dd-WEB-binary

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dd-WEB-binary
        path: dd-WEB-binary
