# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'  # 设置合适的 Go 版本，根据你的项目要求更改

    - name: Build binary
      run: go build -o dd-web  # 这里的 "dd-web" 是编译后的二进制文件名，您可以根据需要更改

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dd-web-binary
        path: dd-web  # 这里的路径是编译后的二进制文件路径
